import Head from 'next/head'
import Layout from '../components/Layout/Layout'
import SignIn from './signin';

export default function Home() {
  return (
    <>
      <Head>
        <title>Beacon Tutors CRM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}


Home.getLayout = function getLayout(page) {
    return <SignIn/>;
};