import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layouts/Layout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Beacon Tutors CRM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}


Home.getLayout = function getLayout(page) {
    return <Layout>{page}</Layout>;
};